DicomText.py - Add options for replacement characters when redacting
SMI/SmiServices pull request #1489
Opened 2023-03-15 08:54 UTC by howff

## Proposed Changes

Allow different options for extracting text from DICOM Structured Reports - including different characters for redacted HTML and newlines/linefeeds/carriage returns.

## Types of changes

What types of changes does your code introduce? Tick all that apply.

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [X] New Feature (non-breaking change which adds functionality)
-   [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation-Only Update (if none of the other choices apply)
    -   In this case, ensure that the message of the head commit from the source branch is prefixed with `[skip ci]`

## Checklist

By opening this PR, I confirm that I have:

-   [X] Reviewed the [contributing](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTING.md) guidelines for this repository
-   [X] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
-   [X] Updated any relevant API documentation
-   [X] Created or updated any tests if relevant
-   [X] Created a [news](https://github.com/SMI/SmiServices/blob/master/news/README.md) file
    -   NOTE: This **_must_** include any changes to any of the following files: default.yaml, any of the RabbitMQ server configurations, GlobalOptions.cs
-   [ ] Listed myself in the [CONTRIBUTORS](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTORS.md) file 🚀
-   [X] Requested a review by one of the repository maintainers

## Issues

If relevant, tag any issues that are _expected_ to be resolved with this PR. E.g.:

-   Closes #1488

2023-03-29 14:00 UTC, jas88 approved these changes
Looks good modulo the missing bit of comment about include_header and the CodeQL point about the <script> regex.

2023-03-29 14:00 UTC, jas88 commented on src/common/Smi_Common_Python/SmiServices/DicomText.py
> +        If include_header is True then (default True).
If include_header is True then ... what?

2023-03-29 14:00 UTC, jas88 commented on src/common/Smi_Common_Python/SmiServices/StringUtils.py
> +    html_str = re.sub('<script[^>]*>.*?</script>', replfunc, html_str, flags=re.I|re.M|re.S)
Looks like CodeQL has a point there, [^>]* in the closing tag part as well as the opening?

2023-03-29 14:19 UTC, rkm requested changes

2023-03-29 14:19 UTC, rkm commented on src/applications/SRAnonTool/CTP_DicomToText.py
> +def extract_mongojson(mongojson, output, metadata_output=None, DicomTextArgs = {}):
I think this will cause a subtle bug, because Python is silly - https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

2023-03-29 14:19 UTC, rkm commented on src/applications/SRAnonTool/CTP_DicomToText.py
> +def extract_dicom_file(input, output, metadata_output=None, DicomTextArgs = {}):
Same as above

2023-03-29 14:19 UTC, rkm commented on src/applications/SRAnonTool/CTP_DicomToText.py
> +def extract_file(input, output, metadata_output=None, DicomTextArgs={}):
Same as above

2023-03-29 14:19 UTC, rkm commented on src/common/Smi_Common_Python/SmiServices/StringUtils.py
> +#!/usr/bin/env python3
Don't think this is needed unless the script will be executed directly?

2023-03-29 14:19 UTC, rkm commented on src/common/Smi_Common_Python/SmiServices/StringUtils.py
> +def string_match(str1, str2):
maybe clarify what this does by renaming to `semehr_string_match` or something?

2023-03-29 14:19 UTC, rkm commented on src/common/Smi_Common_Python/SmiServices/StructuredReport.py
> +    os.remove(tmpfile)
I'd change this to use the context manager so the file is cleaned up automatically (https://docs.python.org/3/library/tempfile.html#examples).

2023-03-30 01:08 UTC, jas88 approved these changes
Looks OK apart from the tag/entity inconsistency noted.

2023-03-30 01:08 UTC, jas88 commented on src/common/Smi_Common_Python/SmiServices/DicomText.py
>      _replace_HTML_entities = True    # replace HTML tags with same length of space chars
Is this actually about entities (such as &amp;pound;) or tags? The only entity I saw handled was &nbsp;, the rest seem to be ignored?

2023-03-30 07:11 UTC, rkm approved these changes

2023-03-30 12:04 UTC, howff commented
Sorry, indentation broke somehow in a test so another review is needed before it can be merged. Thanks!

2023-03-30 14:40 UTC, jas88 approved these changes

2023-03-31 12:38 UTC, rkm approved these changes

2023-03-31 12:47 UTC, merged